services:
  db:
    image: postgres:16.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: brazil-states-cities-rails
    ports:
      - "5432:5432"
  web:
    build: .
    command: ["./entrypoint.sh"]
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db/brazil-states-cities-rails
